version: '3'
services:
  rgs:
    container_name: rgs-site
    build: 
      context: ./site
      dockerfile: Dockerfile.local
    env_file:
      - .env
      - .env.local
    volumes:
      - ./site/api/app:/var/www/api/app
      - ./site/api/src:/var/www/api/src
      - ./site/api/templates:/var/www/api/templates
      - ./site/api/composer.json:/var/www/api/composer.json
      - ./site/public_html:/var/www/html
      - ./logs:/var/log/apache2
    expose:
      - 80
    network_mode: "host"